name: Run tests on push

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Vitest
        run: npm install vitest

      - name: Run tests with Vitest
        run: npx vitest run

      # - name: Annotate PR
      #   if: failure()
      #   run: echo "##[error] Tests failed" >> $GITHUB_ENV
