name: Run tests on push

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13'

    - name: Install dependencies
      run: npm install

    - name: Install Vitest
      run: npm install vitest

    - name: Run tests with Vitest
      run: npx vitest run

    - name: Annotate PR
      if: failure()
      run: exit 1
